#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

MESH_DIR="/home/felix/sphereCases/sphereMesh/sphereBlockMesh/constant/polyMesh"

mkdir constant
cp -r $MESH_DIR constant

runApplication topoSet
runApplication subsetMesh -overwrite remainCells -patch symmetry
runApplication createPatch -overwrite
touch case.foam

#------------------------------------------------------------------------------
