#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

# runApplication blockMesh
# runApplication topoSet
# runApplication subsetMesh -overwrite remainCells -patch symmetry
# runApplication createPatch -overwrite 

# restore0Dir

runApplication decomposePar

runParallel -append "$(getApplication)"


#------------------------------------------------------------------------------
