#!/bin/sh
cd "${0%/*}" || exit 1    # Run from this directory

# Source tutorial run functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"
#------------------------------------------------------------------------------

runApplication surfaceGenerateBoundingBox rocket.stl geometry.stl 2 8 0 2 2 2
runApplication surfaceFeatureEdges -angle 30 geometry.stl geometry.fms

runApplication -overwrite "$(getApplication)"
touch case.foam

#------------------------------------------------------------------------------
