#!/bin/sh
cd "${0%/*}" || exit 1    # Run from this directory

# Source tutorial run functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"
#------------------------------------------------------------------------------

cp ../parts/rocket_1.stl rocket.stl

runApplication surfaceGenerateBoundingBox rocket.stl geometry.stl 2 8 0 2 2 2
rm rocket.stl

runApplication surfaceFeatureEdges -angle 30 geometry.stl geometry.fms

runApplication -overwrite "$(getApplication)"

touch case.foam

runApplication -overwrite checkMesh -allTopology -allGeometry
runApplication -overwrite createPatch -overwrite

#------------------------------------------------------------------------------
